[mongodb]
connection_string = "mongodb+srv://anythingsane:10987654321@cluster0.wvkiv4p.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
database_name = "elhub"
collection_name = "production_mbahour"